app = "vvf-ferie-bot"
primary_region = "fra"

[build]

[env]
  DATABASE_PATH = "/data/vvf_ferie.db"

[[mounts]]
  source = "vvf_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
